vich_uploader:
    db_driver: orm        # or mongodb or propel or phpcr - default db driver
    templating: true      # set to false to disable templating integration
    twig: true            # set to false to disable twig integration (requires templating)
    form: true            # set to false to disable form integration
    storage: file_system  # or gaufrette or flysystem
    metadata:
        auto_detection: true
        cache: file
    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        event_image:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
